## 1. 텐서 (Tensor)

Tensor 자료구조는 numpy의 ndarray와 유사한 개념이다.

GPU 혹은 다른 하드웨어 가속기에서 실행할 수 있는 점이 특징이다.

PyTorch에서는 텐서를 사용하여 모델의 input, output, 모델의 parameter들을 encode한다.

In [66]:
import torch
import numpy as np

### 1. Initializing a Tensor

**Directly from data**

In [67]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


**From a NumPy array**

In [68]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


**From another tensor**

The shape and the datatype(dtype) will be followed.

In [69]:
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n {x_ones} \n')

# overrides the datatype of x_data
x_random = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor: \n {x_random} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1169, 0.2644],
        [0.7014, 0.3806]]) 



**Created with a function**

In [70]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
print(f'Rand tensor: \n {rand_tensor} \n')

ones_tensor = torch.ones(shape)
print(f'Ones tensor: \n {ones_tensor} \n')

zeros_tensor = torch.zeros(shape)
print(f'Zeros tensor: \n {zeros_tensor} \n')

Rand tensor: 
 tensor([[0.6881, 0.9363, 0.5332],
        [0.1606, 0.5338, 0.8581]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



### 2. Attributes of a Tensor

In [71]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 3. Operations on Tensors

**Move tensor to GPU if available**

In [72]:
tensor1 = torch.rand(3, 4)
tensor2 = torch.rand(3, 4)

# Nvidia GPU
if torch.cuda.is_available():
    tensor2 = tensor.to('cuda')


# MPS GPU e.g. MacOS M1
if torch.backends.mps.is_available():
    tensor2 = tensor.to('mps:0')

print(f'Where the tensor1 is: {tensor1.device}')
print(f'Where the tensor2 is: {tensor2.device}')

Where the tensor1 is: cpu
Where the tensor2 is: mps:0


**Numpy-like indexing and slicing**

In [73]:
tensor = torch.ones(4, 4)
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')
print(f'Last column: {tensor[..., -1]}')

tensor[:, 1] = 0
print(f'\nChanged tensor: \n {tensor}')

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])

Changed tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Concatenate tensors**

In [74]:
zeros_tensor = torch.zeros(3, 4)
ones_tensor = torch.ones(3, 4)

# dim default = 0
catted_tensor_0 = torch.cat([zeros_tensor, ones_tensor])
catted_tensor_1 = torch.cat([zeros_tensor, ones_tensor], dim=1)

print(f'Tensor cat dim=0: \n {catted_tensor_0} \n')
print(f'Tensor cat dim=1: \n {catted_tensor_1} \n')

Tensor cat dim=0: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Tensor cat dim=1: 
 tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]]) 



In [75]:
zeros_tensor = torch.zeros(3, 4)
ones_tensor = torch.ones(3, 4)

# dim default = 0
stacked_tensor_0 = torch.stack([zeros_tensor, ones_tensor])
stacked_tensor_1 = torch.stack([zeros_tensor, ones_tensor], dim=1)

print(f'Tensor satck dim=0: \n {stacked_tensor_0} \n')
print(f'Tensor satck dim=1: \n {stacked_tensor_1} \n')

Tensor satck dim=0: 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 

Tensor satck dim=1: 
 tensor([[[0., 0., 0., 0.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [1., 1., 1., 1.]]]) 



**Arithmetic operations**

In [76]:
t1 = torch.rand(3, 4)
t2 = torch.rand(3, 4)

# Multiplication, transpose
y1 = t1 @ t2.T
y2 = t1.matmul(t2.T)

y3 = torch.zeros(3, 3)
torch.matmul(t1, t2.T, out=y3)

print(f'y1 == y2: {torch.equal(y1, y2)}')
print(f'y2 == y3: {torch.equal(y2, y3)}')

y1 == y2: True
y2 == y3: True


**Single-element tensors**

In [77]:
ones_tensor = torch.ones(4, 3)
agg = ones_tensor.sum()

print(f'agg: {agg}')
print(f'Type of agg: {type(agg)}')
print()
print(f'agg_item: {agg.item()}')
print(f'Type of agg_item: {type(agg.item())}')

agg: 12.0
Type of agg: <class 'torch.Tensor'>

agg_item: 12.0
Type of agg_item: <class 'float'>


**In-place operations**

Operations that store the result into the operand.

They have '_' suffix

In [78]:
ones_tensor = torch.ones(4, 3)

result = ones_tensor.add(3)
print(f'ones_tensor after add(): \n {ones_tensor} \n')
print(f'Result of add(): \n {result} \n')

ones_tensor.add_(3)
print(f'ones_tensor after add_(): \n {ones_tensor}')

ones_tensor after add(): 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Result of add(): 
 tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]) 

ones_tensor after add_(): 
 tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


## 4. Bridge with NumPy

**Change between Tensor and NumPy array**

In [79]:
tensor = torch.ones(5)
print(f'tensor: {tensor}')

n = tensor.numpy()
print(f'n: {n}')

t = torch.from_numpy(n)
print(f't: {t}')

tensor: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.])


**Reflection between Tensor and NumPy**

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [80]:
t = torch.ones(5)
n = t.numpy()

t.add_(5)

print(f'n: {n}')

n: [6. 6. 6. 6. 6.]


In [81]:
n = np.ones(5)
t = torch.from_numpy(n)

n += 5

print(f't: {t}')

t: tensor([6., 6., 6., 6., 6.], dtype=torch.float64)


In [82]:
# ???
n = np.ones(5, dtype=int)
t = torch.from_numpy(n)

if torch.backends.mps.is_available():
    t.to('mps:0')

t.add_(5)

print(f'n: {n}')

n: [6 6 6 6 6]
